spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never


  modulith:
    republish-outstanding-events-on-restart: false


#spring.modulith.events.jdbc-schema-initialization.enabled=false